spring:
  application:
    name: microservices-patient
  config:
    import: optional:configserver:http://${SPRING_SECURITY_USERNAME}:${SPRING_SECURITY_PASSWORD}@${CONFIG_SERVER_URL}:${CONFIG_SERVER_PORT}
