spring:
  application.name: predictor
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/patientdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true