version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patientdb
    ports:
      - "5432:5432"
    volumes:
      - ./backend-patient/src/main/resources/data/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medilabo-network

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: notes
    ports:
      - "27017:27017"
    volumes:
      - ./notes/src/main/resources/data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db/
    networks:
      - medilabo-network

  eureka:
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      config:
        condition: service_healthy
    environment:
      CONFIG_SERVER_URL: config
      CONFIG_SERVER_PORT: 9101
      SPRING_SECURITY_USERNAME: root
      SPRING_SECURITY_PASSWORD: s3cr3t
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    networks:
      - medilabo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  patients:
    build:
      context: ./backend-patient
      dockerfile: Dockerfile
    container_name: patients
    environment:
      CONFIG_SERVER_URL: config
      CONFIG_SERVER_PORT: 9101
      SPRING_SECURITY_USERNAME: root
      SPRING_SECURITY_PASSWORD: s3cr3t
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - medilabo-network

  notes:
    build:
      context: ./notes
      dockerfile: Dockerfile
    container_name: notes
    environment:
      CONFIG_SERVER_URL: config
      CONFIG_SERVER_PORT: 9101
      SPRING_SECURITY_USERNAME: root
      SPRING_SECURITY_PASSWORD: s3cr3t
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - medilabo-network

  risk:
    build:
      context: ./risk
      dockerfile: Dockerfile
    container_name: risk
    environment:
      CONFIG_SERVER_URL: config
      CONFIG_SERVER_PORT: 9101
      SPRING_SECURITY_USERNAME: root
      SPRING_SECURITY_PASSWORD: s3cr3t
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    networks:
      - medilabo-network

  gateway:
    container_name: gateway
    ports:
      - "8080:8080"
    build:
      context: ./cloud-gateway
      dockerfile: Dockerfile
    environment:
      CONFIG_SERVER_URL: config
      CONFIG_SERVER_PORT: 9101
      SPRING_SECURITY_USERNAME: root
      SPRING_SECURITY_PASSWORD: s3cr3t
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
      patients:
        condition: service_started
      notes:
        condition: service_started
      risk:
        condition: service_started
    networks:
      - medilabo-network
  
  config:
    container_name: config
    build:
      context: ./config.server
      dockerfile: Dockerfile
    environment:
      CONFIG_SERVER_PORT: 9101
      SPRING_SECURITY_USERNAME: root
      SPRING_SECURITY_PASSWORD: s3cr3t
    networks:
      - medilabo-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9101/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  nextjs:
    build:
      context: ./client-ui
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    networks:
      - medilabo-network

volumes:
  postgres_data:
  mongodb_data:

networks:
  medilabo-network:
    name: medilabo-network
    driver: bridge
