server:
  port: 4001
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.14
eureka:
  client:
    enabled: false
