server:
  port: 4001
spring:
  application.name: notes
  data:
    mongodb:
      host: localhost
      port: 20017
      database: patients
      username: user
      password: password
eureka:
  client:
    enabled: false